FROM ubuntu:20.04
RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN pip3 install --upgrade pip
RUN pip install pandas sqlalchemy apache-airflow great_expectations kubernetes
RUN apt-get install -y vim
RUN airflow db init
RUN airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email 'kevin@buffr.ai'
ENV AIRFLOW_HOME=/root/airflow
ENV PYTHONPATH="${PYTHONPATH}:${AIRFLOW_HOME}"
WORKDIR /app
COPY /app .
ENTRYPOINT ["/bin/bash"]